---
  - hosts: ec2
    become: true
    tasks:
      - name: Installing required packages 
        apt: name={{item}} state=present update_cache=yes
        with_items:
          - python-pip
          - wget
          - vim
          - tcpdump
          - curl
